# Generated by Django 5.0.3 on 2024-04-13 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modelactor',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='fotoActor/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='modeldirector',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='fotoDirector/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='modelactor',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='modelactor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Актер'),
        ),
        migrations.AlterField(
            model_name='modeldirector',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='modeldirector',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='modelgenre',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='actor',
            field=models.ManyToManyField(to='kino.modelactor', verbose_name='Актеры'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kino.modeldirector', verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='file',
            field=models.URLField(blank=True, null=True, verbose_name='Трейлер'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kino.modelgenre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='podpiska',
            field=models.ManyToManyField(to='kino.modelpodpiska', verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='posters/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='modelotziv',
            name='user',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='modelpodpiska',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='modelpodpiska',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
    ]
